config/routes.rb
Rails.application.routes.draw do
  resources :to_do_lists
  root 'to_do_lists#index'
  get 'home/trash_em'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/to_do_list.rb
class ToDoList < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

app/controllers/to_do_lists_controller.rb
class ToDoListsController < ApplicationController
  before_action :set_to_do_list, only: %i[ show edit update destroy ]

  # GET /to_do_lists or /to_do_lists.json
  def index
    @to_do_list = ToDoList.new
    @to_do_lists = ToDoList.all
  end

  # GET /to_do_lists/1 or /to_do_lists/1.json
  def show
  end

  # GET /to_do_lists/new
  def new
    @to_do_list = ToDoList.new
  end

  # GET /to_do_lists/1/edit
  def edit
  end

  # POST /to_do_lists or /to_do_lists.json
  def create
    @to_do_list = ToDoList.new(to_do_list_params)

    respond_to do |format|
      if @to_do_list.save
        format.html { redirect_to to_do_list_url(@to_do_list), notice: "To-Do List item was successfully created." }
        format.json { render :show, status: :created, location: @to_do_list }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @to_do_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /to_do_lists/1 or /to_do_lists/1.json
  def update
    respond_to do |format|
      if @to_do_list.update(to_do_list_params)
        format.html { redirect_to to_do_list_url(@to_do_list), notice: "To-Do List item was successfully updated." }
        format.json { render :show, status: :ok, location: @to_do_list }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @to_do_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /to_do_lists/1 or /to_do_lists/1.json
  def destroy
    @to_do_list.destroy

    respond_to do |format|
      format.html { redirect_to to_do_lists_url, notice: "To-Do List item was successfully deleted." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_to_do_list
      @to_do_list = ToDoList.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def to_do_list_params
      params.require(:to_do_list).permit(:description, :completed)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/to_do_lists_helper.rb
module ToDoListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Toodoo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

<%= render "navbar" %>
<div>
  <body>
    <%= yield %>
  </body>
</div>
</html>

app/views/to_do_lists/_form.html.erb
<%= form_with(model: to_do_list) do |form| %>
  <% if to_do_list.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(to_do_list.errors.count, "error") %> prohibited this to_do_list from being saved:</h2>

      <ul>
        <% to_do_list.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div class="mt-4 p-5 bg-primary text-white rounded">

  <div>
    Add or Edit List Item
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :completed, style: "display: block" %>
    <%= form.check_box :completed %>
  </div>

  <div>
    <%= form.submit "Create/Edit To-Do Item", class: 'btn btn-dark' %>
  </div>

</div>
<% end %>

app/views/to_do_lists/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">

    <a class="navbar-brand" href="#"><%= link_to "To-Do List", root_path %></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

      </ul>
    </div>
  </div>
</nav>

app/views/to_do_lists/_to_do_list.html.erb
<div id="<%= dom_id to_do_list %>">
  <p>
    <strong>Description:</strong>
    <%= to_do_list.description %>
  </p>

  <p>
    <strong>Completed:</strong>
    <%= to_do_list.completed %>
  </p>

</div>

app/views/to_do_lists/edit.html.erb
<h1>Editing To-Do Item</h1>

<div class="card">
  <div class="card-body">
<%= render "form", to_do_list: @to_do_list %>
  </div>
</div>
<br>

<div>
  <%= link_to "Show this To-Do Item", @to_do_list %> |
  <%= link_to "Back to To-Do List", to_do_lists_path %>
</div>

app/views/to_do_lists/index.html.erb
<p style="color: green"><%= notice %></p>

<center>
<div class="card">
  <div class="card-body">
<%= render "form", to_do_list: @to_do_list %>
</div>
</div>
</center>

<div class="card">
<div class="card-body">
<div id="to_do_lists">
  <% @to_do_lists.each do |to_do_list| %>
    <%= render to_do_list %>
    
      <%= link_to "Show this To-Do Item", to_do_list %>
    </p>
</div>
</div>
</div>
<% end %>

app/views/to_do_lists/new.html.erb
<h1>New to do list</h1>

<%= render "form", to_do_list: @to_do_list %>

<br>

<div>
  <%= link_to "Back to To-Do List", to_do_lists_path %>
</div>

app/views/to_do_lists/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @to_do_list %>

<div>
  <%= link_to "Edit this To-Do Items", edit_to_do_list_path(@to_do_list) %> |
  <%= link_to "Back to To-Do List", to_do_lists_path %>

  <%= button_to "Delete this To-Do Item", @to_do_list, class:"btn btn-danger", method: :delete %>
</div>